# Computation on Arrays: broadcasting

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([5,5,5])
a+b

array([5, 6, 7])

In [3]:
a + 5

array([5, 6, 7])

In [4]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [6]:
a = np.arange(3)
b = np.arange(3)[:,np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [7]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [8]:
M = np.ones((2,3))

In [10]:
a = np.arange(3,)

In [11]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [15]:
a = np.arange(3).reshape((3,1))
a

array([[0],
       [1],
       [2]])

In [16]:
b = np.arange(3,)
b

array([0, 1, 2])

In [14]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [18]:
M = np.ones((3,2))
a = np.arange(3)
M


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
a

array([0, 1, 2])

In [ ]:
M + a

In [21]:
a[:,np.newaxis].shape

(3, 1)

In [23]:
M + a[:,np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

## Broadcasting in Practice

### Centering an Array

In [24]:
X =  np.random.random((10,3))

In [25]:
X

array([[0.19315057, 0.89085852, 0.52462232],
       [0.96394077, 0.74118292, 0.72011228],
       [0.4962743 , 0.48291619, 0.50112586],
       [0.7826993 , 0.13080935, 0.6612526 ],
       [0.42206017, 0.79616954, 0.54382465],
       [0.39873126, 0.85538881, 0.8979591 ],
       [0.49121395, 0.33543316, 0.45935987],
       [0.09781735, 0.74855001, 0.67370784],
       [0.13313402, 0.05415416, 0.70390317],
       [0.82978314, 0.35434058, 0.79905831]])

In [26]:
Xmean = X.mean(0)

In [27]:
Xmean

array([0.48088048, 0.53898033, 0.6484926 ])

In [28]:
X_centered = X - Xmean

In [29]:
X_centered

array([[-0.28772991,  0.3518782 , -0.12387028],
       [ 0.48306028,  0.20220259,  0.07161968],
       [ 0.01539381, -0.05606414, -0.14736674],
       [ 0.30181881, -0.40817097,  0.01276   ],
       [-0.05882031,  0.25718922, -0.10466795],
       [-0.08214922,  0.31640848,  0.2494665 ],
       [ 0.01033347, -0.20354716, -0.18913273],
       [-0.38306313,  0.20956969,  0.02521524],
       [-0.34774646, -0.48482617,  0.05541056],
       [ 0.34890266, -0.18463974,  0.15056571]])

In [30]:
X_centered.mean(0)

array([ 8.88178420e-17, -1.11022302e-17, -7.77156117e-17])

Plotting two dimensional Functions

In [32]:
x = np.linspace(0,5,50)
y = np.linspace(0,5,50)[:, np.newaxis]