# aggregations: Min, Max and others

In [2]:
import numpy as np

L = np.random.random(100)
sum(L)

52.65838354803323

In [3]:
np.sum(L)

52.658383548033235

In [4]:
big_array = np.random.rand(1000000)


In [5]:
%timeit sum(big_array)

60 ms ± 3.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit np.sum(big_array)

1.18 ms ± 239 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


Min and Max

In [7]:
min(big_array), max(big_array)

(4.1860277333327645e-07, 0.9999970750105304)

Numpy's corresponding functions have similar syntax and again operate much more quickly:

In [8]:
np.min(big_array), np.max(big_array)

(4.1860277333327645e-07, 0.9999970750105304)

In [9]:
%timeit min(big_array)
%timeit np.min(big_array)

32 ms ± 325 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
439 µs ± 28.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
print(big_array.min(), big_array.max(),big_array.sum())

4.1860277333327645e-07 0.9999970750105304 500127.62989501795


# Multi Dimenesional aggregates

In [12]:
M = np.random.random((3,4))

In [13]:
print(M)

[[0.34720333 0.2920836  0.79250189 0.04783029]
 [0.34328527 0.95148758 0.36447002 0.69307185]
 [0.87374146 0.47705332 0.05758077 0.87597544]]


In [14]:
M.sum()

6.116284810825596

In [15]:
M.sum(axis=0) #adds vertically

array([1.56423006, 1.7206245 , 1.21455267, 1.61687758])

In [16]:
M.sum(axis=1) #adds horizontally

array([1.47961911, 2.35231472, 2.28435098])

In [17]:
M.min(axis=0)

array([0.34328527, 0.2920836 , 0.05758077, 0.04783029])

In [21]:
!head -4 ../Class-Lecture/president_heights.csv

'head' is not recognized as an internal or external command,
operable program or batch file.
