<a href="https://colab.research.google.com/github/belanasaikiran/CSE-5717-Big-Data-Analytics/blob/main/02_01_CreatingNumpyArrays_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).*


# Creating Arrays from Python Lists

## NumPy:
NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant.


In [4]:
import numpy as np
#importing numpy library. It is build on C, so faster operations such as array creations, slicing, modifying elements.

To Create arrays from python lists, we can use `np.array`

In [5]:
#integer array:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

> Numpy is contrained to arrays that contain the same data type. Make sure types match.

---
Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type.
If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):


In [8]:
np.array([3, 1.4]) # this will take default as floating number


array([3. , 1.4])

In [10]:
np.array([1, "Sai Kiran"]) # makes 1 as string datatype

array(['1', 'Sai Kiran'], dtype='<U21')

For a specific data type, use `dtype` keyword

In [11]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional; here's one way of initializing a multidimensional array using a list of lists:


In [15]:
# nested lists result in multi-dimentional arrays
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.
Here are several examples: