<a href="https://colab.research.google.com/github/belanasaikiran/CSE-5717-Big-Data-Analytics/blob/main/Mid_term.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.random.randint(10, size=(4,5,6))

In [2]:
x.ndim

3

In [3]:
x.shape

(4, 5, 6)

In [4]:
x.size

120

In [5]:
x = np.arange(9).reshape((3,3))
print(x[1,1])

4


In [6]:
x[:1]

array([[0, 1, 2]])

In [7]:
x[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [8]:
x = np.arange(16).reshape((4,4))

x_sub = x[:2, :2]

x_sub

array([[0, 1],
       [4, 5]])

In [9]:
x_sub[0][0] = 5

np.sum(x, axis = 0)[0]

29

In [10]:
x = np.array([1,2,3])
y = np.array([[1,2,3]])

In [11]:
x.shape

(3,)

# come back here
4 th question

In [12]:
y.shape

(1, 3)

In [13]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [14]:
%timeit x + 2

1.76 µs ± 488 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
%timeit np.add(x, 2) # confirm

1.14 µs ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
x = np.array([1,2,3])
y = np.array([1,2,3]).reshape((3,1))
x*x*y

array([[ 1,  4,  9],
       [ 2,  8, 18],
       [ 3, 12, 27]])

In [17]:
import pandas as pd

In [25]:
data = pd.read_csv("./train.csv")

In [26]:
data.head()

x1        x2        x3        x4        x5         x6        x7        x8  \
0  1.0  0.026761 -0.620259 -0.892886  1.171058  -1.932229 -5.153764 -2.129748   
1  1.0 -0.165811 -0.748739  0.351256  0.345646  -3.694768 -1.859598  3.141265   
2  2.0 -1.639684  0.966960 -4.105156 -7.102068 -10.245937 -6.495981 -5.775185   
3  3.0  0.392119  0.201262 -0.808156  1.699695   0.468696  9.358398 -5.689655   
4  1.0 -0.362154  1.096581 -2.209181  1.430510  -3.040553 -0.556315 -3.125322   

         x9       x10  ...        x17        x18        x19        x20  \
0  2.313411 -2.009202  ...  11.882210   9.884163 -10.344449  11.634817   
1 -1.101936  2.876558  ...  16.661572   5.165378  14.950746   0.156548   
2  4.720946 -4.664918  ...  16.799698 -15.435145  10.807349   9.535390   
3 -3.418913  3.456031  ...  -3.148217   0.918380  21.656966  14.706890   
4  8.309720 -5.227715  ...   2.679380   3.466357   2.885528   7.154526   

         x21       x22       x23       x24       x25    y  
0  15.934457 -1.004876 -0.559616  0.425215  0.755477  0.0  
1 -24.005558 -0.760881  2.703514  0.020142  1.833380  0.0  
2  -1.323079  0.572417  0.797471 -0.857424  1.103354  1.0  
3  35.167532  0.399151 -0.763947  0.288066 -0.589866  1.0  
4  -3.024414  0.745007 -0.081027 -1.536186 -0.273531  0.0  

[5 rows x 26 columns]

In [28]:
data.describe()

x1           x2           x3           x4           x5  \
count  7500.000000  7500.000000  7500.000000  7500.000000  7500.000000   
mean      1.843067     0.051517     0.168138     0.216066     0.350962   
std       0.853621     0.797982     1.577992     2.367254     3.156170   
min       1.000000    -3.317763    -6.031931   -10.497184   -15.597329   
25%       1.000000    -0.423681    -0.758705    -1.165111    -1.506647   
50%       2.000000     0.039337     0.115522     0.188675     0.372663   
75%       3.000000     0.504788     1.087809     1.594673     2.209389   
max       3.000000     3.717462     6.617456    11.496319    14.174944   

                x6           x7           x8           x9          x10  ...  \
count  7500.000000  7500.000000  7500.000000  7500.000000  7500.000000  ...   
mean      0.472082     0.500805     0.721626     0.766948     0.818067  ...   
std       3.899687     4.788771     5.619513     6.349189     7.188440  ...   
min     -16.667881   -18.318668   -25.862462   -26.907451   -29.242184  ...   
25%      -1.772049    -2.290082    -2.511824    -2.967126    -3.377580  ...   
50%       0.511524     0.522869     0.670736     0.829468     0.773383  ...   
75%       2.781103     3.242105     4.038845     4.492607     5.006287  ...   
max      19.039526    20.006664    24.423756    25.982852    30.435956  ...   

               x17          x18          x19          x20          x21  \
count  7500.000000  7500.000000  7500.000000  7500.000000  7500.000000   
mean      1.279188     1.896591     1.639105     2.102971     2.231801   
std      12.703391    13.265546    13.899751    15.031612    15.629652   
min     -56.916811   -61.961221   -62.344680   -55.443448   -70.544154   
25%      -6.057632    -5.867732    -6.586638    -6.794115    -7.145656   
50%       1.355423     1.931477     1.735362     1.870309     2.290904   
75%       8.867802     9.669442     9.868522    10.971638    11.341827   
max      58.378918    56.667929    66.959747    77.460496    65.621669   

               x22          x23          x24          x25            y  
count  7500.000000  7500.000000  7500.000000  7500.000000  7500.000000  
mean     -0.012986     0.029115    -0.008393    -0.000845     0.502933  
std       0.993627     1.002972     0.991703     0.995305     0.500025  
min      -3.729174    -3.792422    -4.003598    -4.413886     0.000000  
25%      -0.684431    -0.647845    -0.666472    -0.669748     0.000000  
50%      -0.003062     0.027475    -0.011923    -0.008219     1.000000  
75%       0.645228     0.700667     0.649573     0.681323     1.000000  
max       3.329855     3.605568     3.863906     3.558600     1.000000  

[8 rows x 26 columns]

In [29]:
X = data.drop('y', axis=1)  # Feature matrix
y = data['y']  # Labels

In [30]:
from sklearn.ensemble import RandomForestClassifier

forest_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=42)
forest_clf.fit(X, y)


RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=42)

In [31]:
feature_importances = forest_clf.feature_importances_
# Get the feature names after encoding 'x1'
feature_names = X.columns
# Combine importances and names, sort them, and print the top four
important_features = sorted(zip(feature_importances, feature_names), reverse=True)
print("Top 4 important features:", important_features[:4])


Top 4 important features: [(0.3453687049359972, 'x1'), (0.05296601478174079, 'x3'), (0.04481088948386664, 'x16'), (0.03850046688305175, 'x8')]


In [34]:
data.columns

Index(['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11',
       'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20', 'x21',
       'x22', 'x23', 'x24', 'x25', 'y'],
      dtype='object')

In [35]:
data.head()

x1        x2        x3        x4        x5         x6        x7        x8  \
0  1.0  0.026761 -0.620259 -0.892886  1.171058  -1.932229 -5.153764 -2.129748   
1  1.0 -0.165811 -0.748739  0.351256  0.345646  -3.694768 -1.859598  3.141265   
2  2.0 -1.639684  0.966960 -4.105156 -7.102068 -10.245937 -6.495981 -5.775185   
3  3.0  0.392119  0.201262 -0.808156  1.699695   0.468696  9.358398 -5.689655   
4  1.0 -0.362154  1.096581 -2.209181  1.430510  -3.040553 -0.556315 -3.125322   

         x9       x10  ...        x17        x18        x19        x20  \
0  2.313411 -2.009202  ...  11.882210   9.884163 -10.344449  11.634817   
1 -1.101936  2.876558  ...  16.661572   5.165378  14.950746   0.156548   
2  4.720946 -4.664918  ...  16.799698 -15.435145  10.807349   9.535390   
3 -3.418913  3.456031  ...  -3.148217   0.918380  21.656966  14.706890   
4  8.309720 -5.227715  ...   2.679380   3.466357   2.885528   7.154526   

         x21       x22       x23       x24       x25    y  
0  15.934457 -1.004876 -0.559616  0.425215  0.755477  0.0  
1 -24.005558 -0.760881  2.703514  0.020142  1.833380  0.0  
2  -1.323079  0.572417  0.797471 -0.857424  1.103354  1.0  
3  35.167532  0.399151 -0.763947  0.288066 -0.589866  1.0  
4  -3.024414  0.745007 -0.081027 -1.536186 -0.273531  0.0  

[5 rows x 26 columns]

In [44]:
y_label = data['y']
y_label.head()

0    0.0
1    0.0
2    1.0
3    1.0
4    0.0
Name: y, dtype: float64

In [47]:
x_train = data.drop("y", axis=1)
x_train.head()

x1        x2        x3        x4        x5         x6        x7        x8  \
0  1.0  0.026761 -0.620259 -0.892886  1.171058  -1.932229 -5.153764 -2.129748   
1  1.0 -0.165811 -0.748739  0.351256  0.345646  -3.694768 -1.859598  3.141265   
2  2.0 -1.639684  0.966960 -4.105156 -7.102068 -10.245937 -6.495981 -5.775185   
3  3.0  0.392119  0.201262 -0.808156  1.699695   0.468696  9.358398 -5.689655   
4  1.0 -0.362154  1.096581 -2.209181  1.430510  -3.040553 -0.556315 -3.125322   

         x9       x10  ...        x16        x17        x18        x19  \
0  2.313411 -2.009202  ...  -7.057395  11.882210   9.884163 -10.344449   
1 -1.101936  2.876558  ...   2.591090  16.661572   5.165378  14.950746   
2  4.720946 -4.664918  ... -14.741211  16.799698 -15.435145  10.807349   
3 -3.418913  3.456031  ... -25.175711  -3.148217   0.918380  21.656966   
4  8.309720 -5.227715  ...  12.457347   2.679380   3.466357   2.885528   

         x20        x21       x22       x23       x24       x25  
0  11.634817  15.934457 -1.004876 -0.559616  0.425215  0.755477  
1   0.156548 -24.005558 -0.760881  2.703514  0.020142  1.833380  
2   9.535390  -1.323079  0.572417  0.797471 -0.857424  1.103354  
3  14.706890  35.167532  0.399151 -0.763947  0.288066 -0.589866  
4   7.154526  -3.024414  0.745007 -0.081027 -1.536186 -0.273531  

[5 rows x 25 columns]

In [49]:


from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score

# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(data.astype(np.float64))



In [42]:
mlp_clf = MLPClassifier(random_state=42)
rnd_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1, random_state=42)
svm_clf = SVC(probability=True, random_state=42)

In [50]:
cross_val_score(mlp_clf, x_train, y_label, cv=3, scoring="accuracy")

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


array([0.966 , 0.9704, 0.9668])

In [51]:
cross_val_score(rnd_clf, x_train, y_label, cv=3, scoring="accuracy")

array([0.9588, 0.9604, 0.958 ])

In [52]:
cross_val_score(svm_clf, x_train, y_label, cv=3, scoring="accuracy")

array([0.966 , 0.9648, 0.9608])