<a href="https://colab.research.google.com/github/belanasaikiran/CSE-5717-Big-Data-Analytics/blob/main/Mid_term.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

x = np.random.randint(10, size=(4,5,6))

In [5]:
x.ndim

3

In [6]:
x.shape

(4, 5, 6)

In [7]:
x.size

120

In [8]:
x = np.arange(9).reshape((3,3))
print(x[1,1])

4


In [9]:
x[:1]

array([[0, 1, 2]])

In [10]:
x[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [12]:
x = np.arange(16).reshape((4,4))

x_sub = x[:2, :2]

x_sub

array([[0, 1],
       [4, 5]])

In [13]:
x_sub[0][0] = 5

np.sum(x, axis = 0)[0]

29

In [14]:
x = np.array([1,2,3])
y = np.array([[1,2,3]])

In [15]:
x.shape

(3,)

# come back here
4 th question

In [16]:
y.shape

(1, 3)

In [19]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [20]:
%timeit x + 2

2.38 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%timeit np.add(x, 2) # confirm

1.97 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [24]:
x = np.array([1,2,3])
y = np.array([1,2,3]).reshape((3,1))
x*x*y

array([[ 1,  4,  9],
       [ 2,  8, 18],
       [ 3, 12, 27]])